live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin/catppuccin-mocha.toml",
  "~/.config/alacritty/keybindings.toml"
]


[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
# family = "SFMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.94
option_as_alt = "Both"

[window.padding]
x = 6
y = 10
